// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zddbwdandnlbqagcswog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZGJ3ZGFuZG5sYnFhZ2Nzd29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTg0MTksImV4cCI6MjA2NTEzNDQxOX0.7cA4ciurmMzU47-8B3B6pGSkPToMhC9GYvZC3L4_UWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);